sudo: required
dist: trusty
language: node_js
node_js:
  - 13
python:
  - "3.8"

install:
  - npm install jest
  - sudo pip install pytest-cov

script:
  - make test-python
  - make test-js

after_success:
  - DEEPSOURCE_DSN=$PROD_DSN
  - echo $DEEPSOURCEDSN
  - make report-artifacts
