dist: trusty
language: node_js
node_js:
  - 13
python:
  - "3.8"

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - python3 -V
  - pip3 -V

install:
  - npm install jest
  - sudo pip3 install pytest-cov

script:
  - make test-python
  - make test-js

after_success:
  - DEEPSOURCE_DSN=$PROD_DSN
  - echo $DEEPSOURCEDSN
  - make report-artifacts
