name: CI

on:
  pull_request:
  push:
      branches:
      - master

jobs:
    run-tests:
        runs-on: [ubuntu-latest]

        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Install Node
          uses: actions/setup-node@v1
          with:
            node-version: 13.14.0

        - name: Install Jest
          run: npm install jest

        - name: Run tests
          run: |
            npm run test
            # Install DeepSource CLI.
            curl https://deepsource.io/cli | sh
            # See the generated report:
            ls ./coverage/
            # Report the results to DeepSource DEV
            ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./coverage/cobertura-coverage.xml
            
            # Report the results to DeepSource Prod (Currently reporting as python)
            DEEPSOURCE_DSN=${{ secrets.DS_DSN_PROD }} \
            ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage/cobertura-coverage.xml
